language: perl6
sudo: true
#before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq -y libreadline6-dev
perl6:
  - latest
install:
  - rakudobrew build-panda
  - panda installdeps .
  - panda installdeps .
