use v6;
use Inline::Perl5;
# XXX Uses Test::More dynamically

EVAL q:to/EOF/, :lang<perl5>;
#!perl

BEGIN {
  unless ($ENV{RELEASE_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for release candidate testing');
  }
}

# This file was automatically generated by Dist::Zilla::Plugin::MetaTests.

use Test::CPAN::Meta;

meta_yaml_ok();
done_testing;
EOF
